//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppBasite.Models.WebAppModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTION_LOG
    {
        public long ID_LOG { get; set; }
        public string USER_ID { get; set; }
        public string IP_USER { get; set; }
        public Nullable<byte> TYPE { get; set; }
        public Nullable<System.DateTime> DATECREATED { get; set; }
        public string INFORMATION { get; set; }
        public string FIRSTVALUE { get; set; }
        public string SECONDVALUE { get; set; }
    }
}
